sudo: required
services:
  - docker
  

before_install:
  - docker build -t 02mc2473/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run 02mc2473/react-test npm test -- --coverage
  
after_success:
  - docker build -t 02mc2473/multi-client ./client
  - docker build -t 02mc2473/multi-server ./server
  - docker build -t 02mc2473/multi-nginx ./nginx
  - docker build -t 02mc2473/multi-worker ./worker
  
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | 	docker login -u "$DOCKER_ID" --password-stdin
  
  # Take those images and push them to docker hub
  - docker push 02mc2473/multi-client
  - docker push 02mc2473/multi-server
  - docker push 02mc2473/multi-nginx
  - docker push 02mc2473/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: complex
  env: complex-env
  bucket_name: ""
  bucket_path: complex
  on:
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
